version: '3'

services:
  backend:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
#     volumes:
#       - mongodata:/data/db

# volumes:
#   mongodata:
